--- #YAML:1.0
name:               Catalyst-Model-KiokuDB
version:            0.12
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.8
    Catalyst::Plugin::Authentication:  0
    Hash::Util::FieldHash::Compat:  0
    KiokuDB:              0.46
    KiokuX::Model:        0
    KiokuX::User:         0
    Moose:                0
    Scope::Guard:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
