# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Features
version:      0.3.1
version_from: lib/Lingua/Features.pm
installdirs:  site
requires:
    List::Compare:                 0
    Test::More:                    0
    Tie::IxHash:                   0
    XML::Generator:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
